### ISSUE TITLE
Current status?

### ISSUE THREAD

**Issue by TomasVotruba** [HostBox/api-payu-nette-bridge#1]
Hi, I'd like to ask, what's status of this lib? 
I see no tag, but I'd like to use it.

**Comment by pmachan** [comment]
Hi, it's only experimental (now). I need add support for multi shop POS and api-PayU package isn't done yet (its working but refunds are not implemented).

(Plánuju to tedle měsíc dodělat)

**Comment by TomasVotruba** [comment]
Thanks for good news! I'll check this repo when we start to implement this.

GL!

**Comment by pmachan** [comment]
@TomasVotruba Multiple POS now supported :) 811b5658760d7d8ac83f0b8d34d9e40bcb0f6a70

**Comment by TomasVotruba** [comment]
@pmachan Great job! I look forward to using this
