### ISSUE TITLE
Composer require fail

### ISSUE THREAD

**Issue by TomasPilar** [HostBox/api-payu-nette-bridge#2]
Hi, after run `composer require hostbox/api-payu-nette-bridge` i get response:
Problem 1
- Installation request for hostbox/api-payu-nette-bridge ~1.0.0 -> satisfiable by hostbox/api-payu-nette-bridge[v1.0.0].
- hostbox/api-payu-nette-bridge v1.0.0 requires hostbox/api-payu @dev -> no matching package found.

Could you check it, please?
Thanks

**Comment by pmachan** [comment]
@TomasPilaru 
Hi, its my fail :-/ .... Bridge need Api PayU @dev stability.

You need add require for Api PayU too.

```
composer require hostbox/api-payu @dev
composer require hostbox/api-payu-nette-bridge
```

``` json
    "require": {
        "hostbox/api-payu": "@dev",
        "hostbox/api-payu-nette-bridge": "~1.0.0"
    }
```

OR add "minimum-stability": "dev" for your project

**Comment by TomasPilar** [comment]
OK thanks!
